### PR TITLE
Add functions for custom verification emails

### PR DESCRIPTION
**Pull request by wmnnd**
This implements the following new functions:

- `create_custom_verification_email_template/6`
- `update_custom_verification_email_template/1`
- `delete_custom_verification_email_template/1`
- `list_custom_verification_email_templates/1`
- `send_custom_verification_email/3`

It includes a parser for `list_custom_verification_email_templates` and adds a parser for the existing function `list_identities`.

### CODE REVIEW

**Comment by wmnnd** [comment]
While working on this, I noticed some of the code in this repo has not been formatted with `mix format`. I didn’t include this as part of the PR, but could do that if you find it useful.

I also noticed that there aren’t parsers for all queries. Is that on purpose or should all responses have parsers?

**Comment by lessless** [comment]
@wmnnd it's better to format in the separate commit. 

Ideally, all API calls that return XML should have parsers tests - in that way we can have confidence that changes won't break XML parsing. 
Not pretty much needed  for endpoints that return JSON

**Comment by lessless** [comment]
@wmnnd  please add parser tests and I'm ready to merge it in

**Comment by wmnnd** [comment]
Alrighty, I’ll take a shot at the tests.

**Comment by wmnnd** [comment]
@lessless There you go :smiley:

**Review by lessless — CHANGES_REQUESTED** [review]
Sweet! Great job ❤️

**Pull request merged**
