### PR TITLE
Reply to functionality for bulk templated mail

### PR DESCRIPTION
**Pull request by bruce-brookshire**
Added reply_to option to send_bulk_templated_email, and changed the function specs of send_bulk_templated_email and send_templated_email to accept reply_to option. Tests for send_bulk_templated_email reflect this added functionality.

### CODE REVIEW

**Comment by benwilson512** [comment]
Thanks!

**Comment by bruce-brookshire** [comment]
No problem! Glad to help.

**Comment by bruce-brookshire** [comment]
Do you have an idea on when this will be release?

**Comment by lessless** [comment]
@flyrboy96 available as 2.1.1 

https://hex.pm/packages/ex_aws_ses
https://github.com/ex-aws/ex_aws_ses/blob/master/CHANGELOG.md

**Comment by bruce-brookshire** [comment]
@lessless Perfect. Thank you very much

**Pull request merged**
