### PR TITLE
add support for SES API v2 with contact lists & contacts

### PR DESCRIPTION
**Pull request by j4p3**
SES API V2 includes features for list, topic, and subscription management, which can be useful for allowing a recipient to unsubscribe from a topic. This PR adds support for CRUD actions on contact list and contact resources, and for the v2 API's send email endpoint.

Examples:

```
ExAws.SES.create_contact_list("test_list", tags: [%{Key: "environment", Value: "test"}])

ExAws.SES.update_contact_list("test_list", topics: [%{DefaultSubscriptionStatus: "OPT_OUT", DisplayName: "test topic", TopicName: "test_topic"}])

ExAws.SES.create_contact("test_list", "test@example.com", topic_preferences: [%{TopicName: "test_topic", SubscriptionStatus: "OPT_IN"}])

ExAws.SES.send_email_v2(destination, content, "test@example.com", list_management: %{ContactListName: "test_list", TopicName: "test_topic"})
```

### CODE REVIEW

**Comment by lessless** [comment]
Thanks, @j4p3 !

I'll take a look ASAP

**Comment by lessless** [comment]
@j4p3 looks good! 

Can you please also add parser tests https://github.com/ex-aws/ex_aws_ses/blob/master/test/lib/ses/parser_test.exs ?

**Comment by j4p3** [comment]
> @j4p3 looks good!
> 
> Can you please also add parser tests https://github.com/ex-aws/ex_aws_ses/blob/master/test/lib/ses/parser_test.exs ?

@lessless This PR doesn't make any changes to the parser; the v2 API returns JSON instead of XML (https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_GetContact.html#API_GetContact_ResponseSyntax).

So for instance, passing an operation constructed by `ExAws.SES.get_contact` to ExAws `request` would return a tuple with a map of response data, without needing to be passed to the parser.

```
{:ok,                                                                                                                                                                                                                            
 %{                                                                                                                                                                                                                              
   "AttributesData" => nil,                                                                                                                                                                                                      
   "ContactListName" => "test_list",                                                                                                                                                                                             
   "CreatedTimestamp" => 1618723907.588,                                                                                                                                                                                         
   "EmailAddress" => "test@example.com",                                                                                                                                                                                      
   "LastUpdatedTimestamp" => 1618723907.588,                                                                                                                                                                                     
   "TopicDefaultPreferences" => nil,                                                                                                                                                                                             
   "TopicPreferences" => [                                                                                                                                                                                                       
     %{"SubscriptionStatus" => "OPT_IN", "TopicName" => "test_topic"}                                                                                                                                                            
   ],                                                                                                                                                                                                                            
   "UnsubscribeAll" => false                                                                                    
 }}
 ```

Thoughts?

**Review by lessless — APPROVED** [review]
Great 👍

**Comment by lessless** [comment]
Right. If just pass down the response to the caller and that behavior is already covered by tests then we are good to merge.

**Comment by lessless** [comment]
I'll publish v 2.2.0 today or on Monday https://github.com/ex-aws/ex_aws_ses/blob/master/CHANGELOG.md

**Pull request merged**
